//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Broker1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrokerExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Broker")]
    [System.SerializableAttribute()]
    public partial class BrokerExceptionFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Broker1.IBroker")]
    public interface IBroker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/StoreData", ReplyAction="http://tempuri.org/IBroker/StoreDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(App.Broker1.BrokerExceptionFaultContract), Action="http://tempuri.org/IBroker/StoreDataBrokerExceptionFaultContractFault", Name="BrokerExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Broker")]
        string StoreData(byte[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/StoreData", ReplyAction="http://tempuri.org/IBroker/StoreDataResponse")]
        System.Threading.Tasks.Task<string> StoreDataAsync(byte[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/RetrieveData", ReplyAction="http://tempuri.org/IBroker/RetrieveDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(App.Broker1.BrokerExceptionFaultContract), Action="http://tempuri.org/IBroker/RetrieveDataBrokerExceptionFaultContractFault", Name="BrokerExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Broker")]
        byte[] RetrieveData(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/RetrieveData", ReplyAction="http://tempuri.org/IBroker/RetrieveDataResponse")]
        System.Threading.Tasks.Task<byte[]> RetrieveDataAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/DeleteData", ReplyAction="http://tempuri.org/IBroker/DeleteDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(App.Broker1.BrokerExceptionFaultContract), Action="http://tempuri.org/IBroker/DeleteDataBrokerExceptionFaultContractFault", Name="BrokerExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/Broker")]
        void DeleteData(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroker/DeleteData", ReplyAction="http://tempuri.org/IBroker/DeleteDataResponse")]
        System.Threading.Tasks.Task DeleteDataAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerChannel : App.Broker1.IBroker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerClient : System.ServiceModel.ClientBase<App.Broker1.IBroker>, App.Broker1.IBroker {
        
        public BrokerClient() {
        }
        
        public BrokerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StoreData(byte[] value) {
            return base.Channel.StoreData(value);
        }
        
        public System.Threading.Tasks.Task<string> StoreDataAsync(byte[] value) {
            return base.Channel.StoreDataAsync(value);
        }
        
        public byte[] RetrieveData(string key) {
            return base.Channel.RetrieveData(key);
        }
        
        public System.Threading.Tasks.Task<byte[]> RetrieveDataAsync(string key) {
            return base.Channel.RetrieveDataAsync(key);
        }
        
        public void DeleteData(string key) {
            base.Channel.DeleteData(key);
        }
        
        public System.Threading.Tasks.Task DeleteDataAsync(string key) {
            return base.Channel.DeleteDataAsync(key);
        }
    }
}
